### ISSUE TITLE
Комментарии к заданию

### ISSUE THREAD

**Issue by Frumcheg** [novavovikov/autocomplete-reactJS-#1]
Вот и ответ по тестовому заданию.

Сейчас AutoComplete - это функция. Круто, что реакт позволяет просто писать функцию, из которой он потом сделает компонент. Он будет вызывать ее каждый раз, когда что-то поменяется в props. И весь [этот](https://github.com/novavovikov/autocomplete-reactJS-/blob/master/src/autocomplete.js#L11-L117) код будет вызван. Каждый раз будут создаваться новые [хэндлеры](https://github.com/novavovikov/autocomplete-reactJS-/blob/master/src/autocomplete.js#L13-L70), лучше их создать один раз, а потом только вызывать.

Странно, что [эти функции](https://github.com/novavovikov/autocomplete-reactJS-/blob/master/src/autocomplete.js#L137,L175) не вынесены в файл ./actions.js. Сейчас в каждой из них есть повторяющийся кусок кода, от него можно избавиться, если воспользоваться методом [bindActionCreators](http://redux.js.org/docs/api/bindActionCreators.html).

Когда хочется выбрать что-то из стейта, как [здесь](https://github.com/novavovikov/autocomplete-reactJS-/blob/master/src/autocomplete.js#L124), лучше вынести эту логику в отдельную функцию, назвать её как-нибудь и положить ее в файл с названием selectors.js. Так её можно будет переиспользовать.

[Здесь](https://github.com/novavovikov/autocomplete-reactJS-/blob/master/src/autocomplete.js#L80) ты берешь ссылку на элемент, чтобы потом в хэндлере получить из него значение. На самом деле ссылка не нужна, т.к. onChange принимает значение инпута вторым аргументом.

Нужно что-то сделать с переменной newItemPosition. Её значение берется из store, но почти в каждом хендлере её зачем-то нужно переопределять. Нужно ли её на самом деле класть в store? В целом, нужно использовать неизменяемые значения. Это делает код менее связанным, его проще поддерживать и понимать.

Почему [тут](https://github.com/novavovikov/autocomplete-reactJS-/blob/master/src/autocomplete.js#L104) не стрелочная функция, как везде?

[Эти](https://github.com/novavovikov/autocomplete-reactJS-/blob/master/src/actions/getList.js#L3) переменные на самом деле константы, их можно объявить в месте их использования.

Если есть желание, можешь переписать задание с учетом замечаний, я посмотрю на результат.

**Comment by novavovikov** [comment]
Спасибо за ответ.

Сейчас AutoComplete - это функция. Круто, что реакт позволяет просто писать функцию, из которой он потом сделает компонент. Он будет вызывать ее каждый раз, когда что-то поменяется в props. И весь этот код будет вызван. Каждый раз будут создаваться новые хэндлеры, лучше их создать один раз, а потом только вызывать. - **В данном случае я пошёл через класс, чтобы вызывался метод рендер при изменении state, такой подход приемлем? Если создавать чистые функции, то в любом из случаев он перерисовывает весь компонент, включая хендлеры. Оставил несколько комитов, для того, чтобы самому в нужный момент откатится к прошлому решению + показать мои изыскания в данном вопросе.**

Странно, что эти функции не вынесены в файл ./actions.js. Сейчас в каждой из них есть повторяющийся кусок кода, от него можно избавиться, если воспользоваться методом bindActionCreators. - **Сделал**


Когда хочется выбрать что-то из стейта, как здесь, лучше вынести эту логику в отдельную функцию, назвать её как-нибудь и положить ее в файл с названием selectors.js. Так её можно будет переиспользовать. - **Сделал**

Здесь ты берешь ссылку на элемент, чтобы потом в хэндлере получить из него значение. На самом деле ссылка не нужна, т.к. onChange принимает значение инпута вторым аргументом. - **Вторым аргументом она не принимает значение(или что-то я делаю не так), пошёл несколько иным путём, избавившись от ссылки на элемент**

Нужно что-то сделать с переменной newItemPosition. Её значение берется из store, но почти в каждом хендлере её зачем-то нужно переопределять. Нужно ли её на самом деле класть в store? В целом, нужно использовать неизменяемые значения. Это делает код менее связанным, его проще поддерживать и понимать. - **Была добавлена в store, так как была проблема с постоянной перерисовкой компонента и значение скидывалось на начальное. Сейчас сделал несколько по-иному, но мне также не нравится этот подход или же он имеет место быть?**

Почему тут не стрелочная функция, как везде? - **Исправил**

Эти переменные на самом деле константы, их можно объявить в месте их использования. - **Сделал**

**Comment by Frumcheg** [comment]
Почитай вот эту статью https://facebook.github.io/react/docs/handling-events.html. В ней написано, как правильно биндить this к хэндлерам.

**Comment by novavovikov** [comment]
Сделано.
